name: flutter_doko
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql: 3.0.0
  http: 0.12.0+4
  geolocator: ^7.0.1
  flutter_secure_storage: ^4.1.0
    #nosql
  sembast: ^2.1.1
  get_it: ^4.0.2
  path_provider: ^0.5.0+1
  cupertino_icons: ^1.0.2


  #graphql_flutter:
  #graphql:
  #universal_platform: ^0.1.3
    # https://github.com/flutter/flutter/issues/36126#issuecomment-596215587

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true